apiVersion: v1
kind: Service
metadata:
  name: progapanda-org-service
  labels:
    app.kubernetes.io/name: progapanda-org
    app.kubernetes.io/instance: progapanda-org
    app.kubernetes.io/version: "1"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4567
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: progapanda-org
    app.kubernetes.io/instance: progapanda-org
